---
- hosts: mywebservers
  become: yes
  tasks:
  -  name: I want to install java on ubuntu node.
     apt:
       name:  "{{mywebpackonubuntu}}"
       state: present
  -  name: I want to install java on top of the next ubuntu node.
     apt:
       name: "{{myjavawebpackonubuntu}}" 
       state: present
  -  name: I want to install nginx on 172.31.42.252.
     apt:
       name:  "{{myapppackonubuntu}}"
       state: present     