---
- hosts: mywebservers
  become: yes
  gather_facts: yes
  tasks: 
  - name: I want to install webserver on node side.
    apt:
      name:  "{{mywebpackonubuntu}}"
      state: present 
    when: ansible_os_family=="Debian"
  - name: I want to start the webserver
    service:
      name:  "{{mywebpackonredhat}}"
      state: started
    when: ansible_os_family=="Redhat"  

